apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    tier: front-end
    version: v1
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd