apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    tier: backend-end
    version: v1
spec:
  containers:
  - name: redis
    image: redis
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: Exists