apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    env: dev
spec:
  template:
    metadata:
      labels:
        env: dev
      name: ngnix
    spec: 
      containers:
        - name: nginx-container
          image: nginx
          ports:
          - containerPort: 80
  replicas: 3
