apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-learning
  labels:
    app: nagging-alarm-clock
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: nagging-alarm-clock
        spec:
          restartPolicy: Never
          containers:
            - name: task-runner
              image: busybox
              command: ["sh", "-c", "echo \"wake up, it's job time again\"; sleep 5"]
